apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-backend
  labels:
    app: nestjs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-backend
  template:
    metadata:
      labels:
        app: nestjs-backend
    spec:
      containers:
        - name: nestjs-backend
          image: your-dockerhub-username/nestjs-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/nestjs_db"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-backend-service
spec:
  selector:
    app: nestjs-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
