export * from "./user.entity";
export * from "./login.entity";
export * from "./notification.entity";
export * from "./service.entity";
export * from "./faq.entity";
export * from "./blog.entity";
export * from "./partner.entity";
export * from "./contact.entity";
export * from "./galerie.entity";
export * from "./reservation.entity";
export * from "./review.entity"
